# Generated by Django 5.0.6 on 2024-10-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementpostcontent',
            name='content_url',
            field=models.FileField(upload_to='content_files/'),
        ),
    ]
