# Generated by Django 5.0.6 on 2024-10-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_engagementpostcontent_content_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementpostcontent',
            name='content_url',
            field=models.CharField(max_length=100),
        ),
    ]
